post:
  summary: Login a user
  tags:
    - Auth
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          required:
            - email
            - password
          properties:
            email:
              type: string
              format: email
            password:
              type: string
  responses:
    '200':
      description: User has been logged in
      content:
        application/json:
          schema:
            type: object
            properties:
              token:
                type: string
    '400':
      description: Validation failed
    '401':
      description: Unauthorized
    '500':
      description: Server error
