post:
  summary: Register a new user
  tags:
    - Auth
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          required:
            - name
            - email
            - password
            - role
          properties:
            name:
              type: string
            email:
              type: string
              format: email
            password:
              type: string
            role:
              type: string
  responses:
    '201':
      description: User has been registered
    '400':
      description: Validation failed
    '500':
      description: Server error
