get:
  summary: Get user by ID
  tags:
    - User
  parameters:
    - in: path
      name: id
      required: true
      schema:
        type: string
      description: User ID
  responses:
    '200':
      description: User found. returns user object
    '404':
      description: User not found
    '500':
      description: Server error
