put:
  summary: Update user by ID
  tags:
    - User
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          required:
            - name
            - email
            - role
          properties:
            name:
              type: string
            email:
              type: string
              format: email
            role:
              type: string
  responses:
    '200':
      description: User has been updated
    '400':
      description: Validation failed
    '404':
      description: User not found
    '500':
      description: Server error
delete:
  summary: Delete user by ID
  tags:
    - User
  parameters:
    - in: path
      name: id
      required: true
      schema:
        type: string
      description: User ID
  responses:
    '200':
      description: User has been deleted
    '404':
      description: User not found
    '500':
      description: Server error
