openapi: 3.0.0
info:
  title: OtePal API
  version: 1.0.0
  description: API documentation for the OtePal application
servers:
  - url: http://localhost:3001
tags:
  - name: Auth
    description: User Authentication endpoints
paths:
  $ref: paths/index.yaml
